stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

create-ranking:
  timeout: 5m
  stage: build
  image: node:14
  before_script:
    - mkdir .gcp
    - echo "$GOOGLE_ANALYTICS_CREDENTIALS" > .gcp/google-analytics_credentials.json
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - git remote set-url origin git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    - git checkout $CI_COMMIT_REF_NAME
    - npm ci
    - npm run create-ranking
    - git add ./data
    - git commit -am "Create Ranking"
    - git -c core.sshCommand="ssh -oStrictHostKeyChecking=no" push origin ${CI_COMMIT_REF_NAME}
  only:
    - schedules

pages:
  timeout: 5m
  stage: deploy
  image: node:14
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script: |
    mv exampleContent content
    mv config.org.yml config.yml
    sed -ie "s|baseURL:.*|baseURL: https://okdyy75.com|" config.yml
    sed -ie "s|googleAnalytics:.*|googleAnalytics: G-LR5GBHW5M5|" config.yml
    sed -ie "s|my_name|okdyy75|" config.yml
    sed -ie "s|name: ユーザー名|name: okdyy75|" config.yml
    sed -ie "s|description: プロフィール|description: Hugo用ブログテーマ「Salt」を作りました|" config.yml
    sed -ie "s|twitter: twitter|twitter: okdyy75|" config.yml
    sed -ie "s|github: github|github: okdyy75|" config.yml
    sed -ie "s|qiita: qiita|qiita: okdyy75|" config.yml
    sed -ie "s|zenn: zenn|zenn: okdyy75|" config.yml
    sed -ie "s|email: email@example.com|email: okdyy75@gmail.com|" config.yml
    sed -ie "s|other: https://example.com|other: https://github.com/okdyy75|" config.yml
    echo 'google.com, pub-9459277760652211, DIRECT, f08c47fec0942fa0' > static/ads.txt
    echo '<script> let isLoaded = false; window.addEventListener("scroll", function () { if ((document.documentElement.scrollTop != 0 && isLoaded === false) || (document.body.scrollTop != 0 && isLoaded === false)) { (function () { let e = document.createElement("script"); e.type = "text/javascript"; e.crossorigin = "anonymous"; e.async = true; e.src = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9459277760652211"; document.body.appendChild(e); })(); isLoaded = true; } }, true); </script>' >> ./layouts/partials/body-add.html
    npm run build
  artifacts:
    paths:
      - public
  only:
    - main
    - develop
