
variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  timeout: 5m
  image: node:14
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script: |
    mv exampleContent content
    mv config.org.yml config.yml
    sed -ie "s|baseURL:.*|baseURL: https://okdyy75.com|" config.yml
    echo '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6143606071173887" crossorigin="anonymous"></script>' >> ./layouts/partials/head-script.html
    npm run build
  artifacts:
    paths:
      - public
  only:
    - main
