
variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  timeout: 5m
  image: node:14
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - mv exampleContent content
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - main
