
variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  timeout: 5m
  image: node:14
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script: |
    mv exampleContent content
    mv config.org.yml config.yml
    sed -ie "s|baseURL:.*|baseURL: https://okdyy75.com|" config.yml
    echo '<script data-ad-client="ca-pub-9459277760652211" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>' >> ./layouts/partials/head-add.html
    npm run build
  artifacts:
    paths:
      - public
  only:
    - main
    - develop
