baseURL: https://hugo-theme-salt.okdyy75.com
languageCode: ja
# theme: hugo-theme-salt
title: Hugo用ブログテーマ「Salt」
googleAnalytics: 

taxonomies:
  category: categories
  tag: tags
  pickup: pickups

hasCJKLanguage: true
summaryLength: 200
paginate: 10

markup:
  goldmark:
    renderer:
      unsafe: true

related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 90
  - name: date
    weight: 10
  threshold: 80
  toLower: false

module:
  mounts:
    - source: static
      target: static
    - source: node_modules/@fortawesome/fontawesome-free/css/all.min.css
      target: static/css/vendor/@fortawesome/fontawesome-free/css/all.min.css
    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/css/vendor/@fortawesome/fontawesome-free/webfonts
    - source: node_modules/github-markdown-css/github-markdown.css
      target: static/css/vendor/github-markdown-css/github-markdown.css

params:
  description: このサイトはHugo用ブログテーマ「Salt」のサンプルサイトです
  images:
    - image/og_large.png
  notFoundImage: image/404.png
  dafaultNoimage: image/default_noimage.png
  newArticleLimit: 5
  relatedArticleLimit: 2
  imageQuality: 75
  profile:
    name: ユーザー名
    description: プロフィール
    icon: image/profile_icon.png
    link:
      twitter: twitter
      instagram: instagram
      facebook: https://www.facebook.com/facebook
      youtube: https://www.youtube.com/user/YouTubeJapan
      github: github
      qiita: qiita
      zenn: zenn
      email: email@example.com
      other: https://example.com
  copyright:
    author: 作者
    link: https://example.com
    year: 2021

menu:
  header:
    - name: サンプル
      url: /categories/サンプル
      weight: -100
    - name: テスト
      url: /categories/テスト
      weight: -90
    - name: カテゴリー1
      url: /categories/カテゴリー1
      weight: -80
    - name: カテゴリー2
      url: /categories/カテゴリー2
      weight: -70
  sidebar:
    - name: サンプル
      url: /categories/サンプル
      pre: <i class="fa-2x fas fa-book"></i>
      weight: -100
    - name: テスト
      url: /categories/テスト
      pre: <i class="fa-2x fas fa-laptop-code"></i>
      weight: -90
    - name: カテゴリー1
      url: /categories/カテゴリー1
      pre: <i class="fa-2x fas fa-mobile-alt"></i>
      weight: -80
    - name: カテゴリー2
      url: /categories/カテゴリー2
      pre: <i class="fa-2x fab fa-safari"></i>
      weight: -70
    - name: タグ1
      url: /tags/タグ1
      pre: <i class="fa-2x fas fa-home"></i>
      weight: -60
    - name: タグ2
      url: /tags/タグ2
      pre: <i class="fa-2x fas fa-cog"></i>
      weight: -50
    - name: タグ3
      url: /tags/タグ3
      pre: <i class="fa-2x fas fa-tshirt"></i>
      weight: -40
    - name: タグ4
      url: /tags/タグ4
      pre: <i class="fa-2x far fa-calendar-alt"></i>
      weight: -30
  footer:
    - name: このサイトについて
      url: /about
      weight: -100
      params:
        position: left
    - name: お知らせ
      url: /information
      weight: -90
      params:
        position: left
    - name: 利用規約・プライバシーポリシー
      url: /term
      weight: -100
      params:
        position: right
    - name: お問い合わせ
      url: mailto:email@example.com?subject=お問い合わせ
      weight: -90
      params:
        position: right
