name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: npm Install
      run: |
        npm ci

    - name: Build
      run: |
        echo 'hugo-theme-salt.okdyy75.com' > static/CNAME
        mv exampleContent content
        mv config.org.yml config.yml
        sed -ie "s|googleAnalytics:.*|googleAnalytics: G-LR5GBHW5M5|" config.yml
        sed -ie "s|my_name|okdyy75|" config.yml
        sed -ie "s|name: ユーザー名|name: okdyy75|" config.yml
        sed -ie "s|description: プロフィール|description: Hugo用ブログテーマ「Salt」を作りました|" config.yml
        sed -ie "s|twitter: twitter|twitter: okdyy75|" config.yml
        sed -ie "s|github: github|github: okdyy75|" config.yml
        sed -ie "s|qiita: qiita|qiita: okdyy75|" config.yml
        sed -ie "s|zenn: zenn|zenn: okdyy75|" config.yml
        sed -ie "s|email: email@example.com|email: okdyy75@gmail.com|" config.yml
        sed -ie "s|other: https://example.com|other: https://github.com/okdyy75|" config.yml
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public